name: wifi_state
description: "for checking and opening wifi settings"
version: 0.0.2
homepage: https://github.com/edex96/wifi_state

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wifi_state
        pluginClass: WifiState
